# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stirling Motors Corporation
email1: derek.holsapple@stirlingmotorscorp.com
email2: alan@stirlingmotorscorp.com
description: > # this means to ignore newlines until "baseurl:"
  Stirling Motors Corporation is a startup company that designs, builds,
  and sells Stirling Engines for use in Liquid Pumping, HVAC,
  Refrigeration, and Electric Generator applications.
baseurl: "/stirling_motors" # the subpath of your site, e.g. /blog
url: "http://stirlingmotorscorp.com" # the base hostname & protocol for your site
twitter_username: stirlingmotorc
linkedin_username: company/stirling-motors-corporation
# Build settings
markdown: kramdown
